import type { PaseoApi } from "@getpaseo/client";
import type { ZodType, input as ZodInput, output as ZodOutput } from "zod";
import type { PluginRpcContract, PluginRpcWorkspacePermission } from "../rpc.js";
import type { PluginCleanup } from "../contracts.js";
import type { ProviderRegistration } from "./provider.js";
import type { PluginLifecycleRegistration } from "./lifecycle.js";

/** Host-validated target and a snapshot of the authenticated session's explicit grants.
 * Targets are selected by the caller under global grants, not UI or origin proof.
 * Not derived from RPC input; the plugin's Paseo API remains process-wide.
 */
export interface PluginInvocationContext {
  readonly authentication: {
    readonly kind: "session";
    /** Generated by the host Session; attribution, not a reusable credential. */
    readonly sessionId: string;
    /** Reported client identifier; not an authenticated principal identity. */
    readonly clientId: string;
  };
  readonly workspaceId: string;
  readonly agentId?: string;
  readonly permissions: readonly PluginRpcWorkspacePermission[];
}
export interface PluginHandlerContext {
  paseo: PaseoApi;
  invocation?: PluginInvocationContext;
}

export type PluginSettingsState<Schema extends ZodType> =
  | {
      status: "ready";
      revision: string;
      values: ZodOutput<Schema>;
    }
  | {
      status: "invalid";
      revision: string;
      error: string;
    };

export interface PluginSettings<Schema extends ZodType> {
  read(): Promise<PluginSettingsState<Schema>>;
  subscribe(listener: (state: PluginSettingsState<Schema>) => void | Promise<void>): PluginCleanup;
}

export interface PluginServerContext extends PluginLifecycleRegistration {
  registerSettings<Schema extends ZodType>(
    definition: import("../settings.js").SettingsDefinition<Schema>,
  ): PluginSettings<Schema>;
  handle<InputSchema extends ZodType, OutputSchema extends ZodType>(
    contract: PluginRpcContract<InputSchema, OutputSchema>,
    handler: (
      input: ZodOutput<InputSchema>,
      context: PluginHandlerContext,
    ) => ZodInput<OutputSchema> | Promise<ZodInput<OutputSchema>>,
  ): void;
  registerProvider(provider: ProviderRegistration): void;
}

export type PluginServerContribution = (server: PluginServerContext) => PluginCleanup;
